### ISSUE TITLE
findOne return Object with "Document" metadata

### ISSUE THREAD

**Issue by AurelienC** [dburles/meteor-collection-helpers#77]
Hello,

When I implement `Collection.helpers({});` into a collection, each `Collection.findOne({})` return an `Object` (normal !) but with the _Document_ metadata (see bellow).

This think make problems with my unit test because _deepEqual_ become __false__.

__Without collection helper__
```
I20170424-17:02:08.460(2)? { name: 'sed',
I20170424-17:02:08.460(2)?   number: 24536,
I20170424-17:02:08.461(2)?   part: 'panel',
I20170424-17:02:08.461(2)?   active: true,
I20170424-17:02:08.461(2)?   cron: 3,
I20170424-17:02:08.462(2)?   workshops: [ 'Music' ],
I20170424-17:02:08.462(2)?   connection: { ip: '28.235.157.134' },
I20170424-17:02:08.464(2)?   _id: 'NvQBFSNPgkoEWY9cx' }
```
__With collection helpers__
```
I20170424-17:02:08.468(2)? Document {
I20170424-17:02:08.468(2)?   _id: 'NvQBFSNPgkoEWY9cx',
I20170424-17:02:08.469(2)?   name: 'sed',
I20170424-17:02:08.469(2)?   number: 24536,
I20170424-17:02:08.469(2)?   part: 'panel',
I20170424-17:02:08.470(2)?   active: true,
I20170424-17:02:08.470(2)?   cron: 3,
I20170424-17:02:08.470(2)?   workshops: [ 'Music' ],
I20170424-17:02:08.471(2)?   connection: { ip: '28.235.157.134' } }
```

Why the library do that ?

Thanks !
Aurélien :-)

**Comment by crapthings** [comment]
yeah why ?

Document is prototype of window.document ?

**Comment by dburles** [comment]
It will be an instance of `self._helpers` on the collection. The `Document` function name in hindsight was probably not ideal given it's a reserved DOM API, but it was added since it looks nicer in the console than without it and of no real conflict.

The deepEqual won't work since it's an instance of `Document` rather than a plain object as you would get without the document being 'transformed' through collection helpers.

See here for an example of what's going on, along with a solution to compare transformed documents with `deepEqual`: https://codepen.io/anon/pen/Wjpwee?editors=0010

Hope that help*ers* 😄

**Comment by AurelienC** [comment]
Thanks @dburles 🙂 for your complete response  

I was carry on my development witout helpers for the moment.

I will test your solution if I have a little time ⏳
